# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
    branches:
      - main
  pull_request:
    branches: [ '*' ]
    types: [opened, synchronize, reopened]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  check_run:
    types: [ rerequested, completed ]
  branch_protection_rule:
    types: [ created, deleted ]
  check_suite:
    types: [ completed ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
